Controllers/ClientDataFieldController.cs
using Appointment_calendar.Domain.DatabaseAccess;
using Appointment_calendar.Domain.Entities.Concreate;
using Microsoft.AspNetCore.Mvc;

namespace Language_School.Controllers
{
    public class ClientDataFieldController : Controller
    {
		private readonly ServiceManager serviceManager;

		public ClientDataFieldController(ServiceManager serviceManager)
        {
            this.serviceManager = serviceManager;
        }


        public IActionResult Index(Guid id)
        {
			var entity = serviceManager.TextFields.GetTextFieldByCodeWord("PageClientDataField");
            return View();
        }


        [HttpPost]
        public IActionResult Send(ClientDataField model)
        {
            if (ModelState.IsValid)
            {
				serviceManager.ClientDataFields.SaveClientDataField(model);
                return RedirectToAction("Complete");
            }
            return View();
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Ваша заявка принята";
            return View();
        }
    }
}

Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>


@* asp-append-version: если имеет значение true, то к пути к файлу скрипта добавляется номер версии *@

Views/Shared/FooterPartial.cshtml
<section id="footer">
	<div class="container">
		<header>
			<h2>Questions or comments? <strong>Get in touch:</strong></h2>
		</header>
		<div class="row">
			<div class="col-6 col-12-medium">
				<section>
					<form method="post" action="#">
						<div class="row gtr-50">
							<div class="col-6 col-12-small">
								<input name="name" placeholder="Name" type="text" />
							</div>
							<div class="col-6 col-12-small">
								<input name="email" placeholder="Email" type="text" />
							</div>
							<div class="col-12">
								<textarea name="message" placeholder="Message"></textarea>
							</div>
							<div class="col-12">
								<a href="#" class="form-button-submit button icon solid fa-envelope">Send Message</a>
							</div>
						</div>
					</form>
				</section>
			</div>
			<div class="col-6 col-12-medium">
				<section>
					<p>
						Erat lorem ipsum veroeros consequat magna tempus lorem ipsum consequat Phaselamet
						mollis tortor congue. Sed quis mauris sit amet magna accumsan tristique. Curabitur
						leo nibh, rutrum eu malesuada.
					</p>
					<div class="row">
						<div class="col-6 col-12-small">
							<ul class="icons">
								<li class="icon solid fa-home">
									1234 Somewhere Road<br />
									Nashville, TN 00000<br />
									USA
								</li>
								<li class="icon solid fa-phone">
									(000) 000-0000
								</li>
								<li class="icon solid fa-envelope">
									<a href="#">info@untitled.tld</a>
								</li>
							</ul>
						</div>
						<div class="col-6 col-12-small">
							<ul class="icons">
								<li class="icon brands fa-twitter">
									<a href="#">untitled</a>
								</li>
								<li class="icon brands fa-instagram">
									<a href="#">instagram.com/untitled</a>
								</li>
								<li class="icon brands fa-dribbble">
									<a href="#">dribbble.com/untitled</a>
								</li>
								<li class="icon brands fa-facebook-f">
									<a href="#">facebook.com/untitled</a>
								</li>
							</ul>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
	<div id="copyright" class="container">
		<ul class="links">
			<li>&copy; Untitled. All rights reserved.</li>
			<li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
		</ul>
	</div>
</section>

	</div>

Views/Shared/HeaderPartial.cshtml
<section id="header">
	<div class="container">

		<!-- Logo -->
		<h1><a href="/" id="logo">@BasicInformation.CompanyName</a></h1>

		<!-- Nav -->
		<nav id="nav">
			<ul>
				<li> <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a></li>
				<li> <a asp-area="" asp-controller="Home" asp-action="Services" asp-route-id="">Услуги</a> </li>
				<li> <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a></li>
				<li> <a asp-area="" asp-controller="Home" asp-action="AboutUs">Обо мне</a></li>
				<li> <a asp-area="" asp-controller="ClientDataField" asp-action="Index">Оставить заявку</a></li>

			</ul>
		</nav>

	</div>
</section>
<section id="header">

Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

@if(ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@BasicInformation.CompanyName</title>
}
@if (ViewBag.Description != null)
{
    <title>@ViewBag.Description</title>
}
@if (ViewBag.Keywords != null)
{
    <title>@ViewBag.Keywords</title>
}

Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

Views/Shared/SidebarPartial.cshtml
<div id="sidebar" class="col-4 col-12-medium">

	<!-- Excerpts -->
	<section>
		<ul class="divided">
			<li>

				<!-- Excerpt -->
				<article class="box excerpt">
					<header>
						<span class="date">July 30</span>
						<h3><a href="#">Just another post</a></h3>
					</header>
					<p>
						Lorem ipsum dolor odio facilisis convallis. Etiam non nunc vel est
						suscipit convallis non id orci lorem ipsum sed magna consequat feugiat lorem dolore.
					</p>
				</article>

			</li>
			<li>

				<!-- Excerpt -->
				<article class="box excerpt">
					<header>
						<span class="date">July 28</span>
						<h3><a href="#">And another post</a></h3>
					</header>
					<p>
						Lorem ipsum dolor odio facilisis convallis. Etiam non nunc vel est
						suscipit convallis non id orci lorem ipsum sed magna consequat feugiat lorem dolore.
					</p>
				</article>

			</li>
			<li>

				<!-- Excerpt -->
				<article class="box excerpt">
					<header>
						<span class="date">July 24</span>
						<h3><a href="#">One more post</a></h3>
					</header>
					<p>
						Lorem ipsum dolor odio facilisis convallis. Etiam non nunc vel est
						suscipit convallis non id orci lorem ipsum sed magna consequat feugiat lorem dolore.
					</p>
				</article>

			</li>
		</ul>
	</section>

	<!-- Highlights -->
	<section>
		<ul class="divided">
			<li>

				<!-- Highlight -->
				<article class="box highlight">
					<header>
						<h3><a href="#">Something of note</a></h3>
					</header>
					<a href="#" class="image left"><img src="images/pic06.jpg" alt="" /></a>
					<p>
						Phasellus sed laoreet massa id justo mattis pharetra. Fusce suscipit ligula vel quam
						viverra sit amet mollis tortor congue magna lorem ipsum dolor et quisque ut odio facilisis
						convallis. Etiam non nunc vel est suscipit convallis non id orci. Ut interdum tempus
						facilisis convallis. Etiam non nunc vel est suscipit convallis non id orci.
					</p>
					<ul class="actions">
						<li><a href="#" class="button icon solid fa-file">Learn More</a></li>
					</ul>
				</article>

			</li>
			<li>

				<!-- Highlight -->
				<article class="box highlight">
					<header>
						<h3><a href="#">Something of less note</a></h3>
					</header>
					<a href="#" class="image left"><img src="images/pic07.jpg" alt="" /></a>
					<p>
						Phasellus sed laoreet massa id justo mattis pharetra. Fusce suscipit ligula vel quam
						viverra sit amet mollis tortor congue magna lorem ipsum dolor et quisque ut odio facilisis
						convallis. Etiam non nunc vel est suscipit convallis non id orci. Ut interdum tempus
						facilisis convallis. Etiam non nunc vel est suscipit convallis non id orci.
					</p>
					<ul class="actions">
						<li><a href="#" class="button icon solid fa-file">Learn More</a></li>
					</ul>
				</article>

			</li>
		</ul>
	</section>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<!--
	
-->
<html>
<head>
	@await Html.PartialAsync("CssPartial")
	@await Html.PartialAsync("MetatagsPartial")
	
	
</head>
<body class="right-sidebar is-preload">
	<div id="page-wrapper">

		<!-- Header -->
		@await Html.PartialAsync("HeaderPartial")


		<!-- Main -->
		<section id="main">
			<div class="container">
				<div class="row">

					<!-- Content -->
					<div id="content" class="col-8 col-12-medium">

						@RenderBody()

					</div>

					<!-- Sidebar -->
					@await Html.PartialAsync("SidebarPartial")

				</div>
			</div>
		</section>

		<!-- Footer -->
		@await Html.PartialAsync("FooterPartial")

	<!-- Scripts -->
	@await Html.PartialAsync("ScriptsPartial")

</body>
</html>